server:
  port: 8082
  mode: "dev"
mysql:
  host: 0.0.0.0
  port: 3308
  username: root
  password: root
  dbName: shopdevgo
  maxIdelConns: 10
  maxOpenConns: 100
  connMaxLifeTime: 3600
logger:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_backups: 30
  max_ag: 7
  max_size: 1024
  compress: true
redis:
  host: 127.0.0.1
  port: 6381
  password:
  database: 0
